#pragma once

namespace StringTable::Identifiers::Resource::Planet
{
    constexpr static auto IDC_CONTAINER_MUSIC_HALL  = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL";
    constexpr static auto IDC_RADIO_BEGINNER_01     = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL/IDC_RADIO_BEGINNER_01";
    constexpr static auto IDC_RADIO_BEGINNER_02     = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL/IDC_RADIO_BEGINNER_02";
    constexpr static auto IDC_RADIO_BEGINNER_03     = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL/IDC_RADIO_BEGINNER_03";
    constexpr static auto IDC_RADIO_HIGH_01         = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL/IDC_RADIO_HIGH_01";
    constexpr static auto IDC_RADIO_INTERMEDIATE_01 = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL/IDC_RADIO_INTERMEDIATE_01";
    constexpr static auto IDC_RADIO_PREMIUM_01      = "STATE_PLANET/IDC_CONTAINER_MUSIC_HALL/IDC_RADIO_PREMIUM_01";
    constexpr static auto IDC_CHANNEL_BOARD         = "STATE_PLANET/IDC_CHANNEL_BOARD";
    constexpr static auto IDC_BUTTON_EXIT           = "STATE_PLANET/IDC_BUTTON_EXIT";

    namespace ChannelBoard
    {
        constexpr static auto IDC_CONTAINER_CHANNEL_CONTROLS  = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS";
        constexpr static auto IDC_LIST_CHANNEL                = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_LIST_CHANNEL";
        constexpr static auto IDC_IMAGE_CHANNEL_CATEGORY      = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_IMAGE_CHANNEL_CATEGORY";
        constexpr static auto IDC_BUTTON_CHANNEL_ENTER        = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_BUTTON_CHANNEL_ENTER";
        constexpr static auto IDC_BUTTON_CHANNEL_TAB          = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_BUTTON_CHANNEL_TAB";
        constexpr static auto IDC_BUTTON_NOTICE_TAB           = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_BUTTON_NOTICE_TAB";
        constexpr static auto IDC_IMAGE_CHANNEL_NOTICE        = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_IMAGE_CHANNEL_NOTICE";
        constexpr static auto IDC_NUMBER_CURRENT_CHANNEL_PAGE = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_NUMBER_CURRENT_CHANNEL_PAGE";
        constexpr static auto IDC_NUMBER_MAX_CHANNEL_PAGE     = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_NUMBER_MAX_CHANNEL_PAGE";
        constexpr static auto IDC_BUTTON_CHANNEL_LEFT         = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_BUTTON_CHANNEL_LEFT";
        constexpr static auto IDC_BUTTON_CHANNEL_RIGHT        = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_BUTTON_CHANNEL_RIGHT";

        namespace Require
        {
            constexpr static auto IDC_CHANNEL_BUTTON = "IDC_CHANNEL_BUTTON";
        }

        namespace ChannelButton
        {
            constexpr static auto IDC_NUMBER_CHANNEL_ID     = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_LIST_CHANNEL/IDC_CHANNEL_BUTTON*/IDC_NUMBER_CHANNEL_ID";
            constexpr static auto IDC_IMAGE_CHANNEL_NAME    = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_LIST_CHANNEL/IDC_CHANNEL_BUTTON*/IDC_IMAGE_CHANNEL_NAME";
            constexpr static auto IDC_IMAGE_CHANNEL_FULL    = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_LIST_CHANNEL/IDC_CHANNEL_BUTTON*/IDC_IMAGE_CHANNEL_FULL";
            constexpr static auto IDC_IMAGE_CHANNEL_FOCUS   = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_LIST_CHANNEL/IDC_CHANNEL_BUTTON*/IDC_IMAGE_CHANNEL_FOCUS";
            constexpr static auto IDC_GAUGE_CHANNEL_COUNTER = "STATE_PLANET/IDC_CHANNEL_BOARD/IDC_CONTAINER_CHANNEL_CONTROLS/IDC_LIST_CHANNEL/IDC_CHANNEL_BUTTON*/IDC_GAUGE_CHANNEL_COUNTER";
        }
    }
}
