#pragma once

#include <OTwo/StringTable/Identifiers/Cache.hpp>
#include <OTwo/StringTable/Identifiers/Sound.hpp>
#include <OTwo/StringTable/Identifiers/Avatar.hpp>
#include <OTwo/StringTable/Identifiers/ChatPanel.hpp>
#include <OTwo/StringTable/Identifiers/Map.hpp>
#include <OTwo/StringTable/Identifiers/Instrument.hpp>
#include <OTwo/StringTable/Identifiers/Option.hpp>
#include <OTwo/StringTable/Identifiers/SelectMusic.hpp>
#include <OTwo/StringTable/Identifiers/Game.hpp>
#include <OTwo/StringTable/Identifiers/Planet.hpp>
#include <OTwo/StringTable/Identifiers/Room.hpp>
#include <OTwo/StringTable/Identifiers/Bulletin.hpp>
#include <OTwo/StringTable/Identifiers/MyRoom.hpp>
#include <OTwo/StringTable/Identifiers/ItemShop.hpp>
#include <OTwo/StringTable/Identifiers/Payment.hpp>
#include <OTwo/StringTable/Identifiers/MusicShop.hpp>
#include <OTwo/StringTable/Identifiers/Waiting7K.hpp>
#include <OTwo/StringTable/Identifiers/Playing7K.hpp>
#include <OTwo/StringTable/Identifiers/Result.hpp>
